apps/webapp/urls.py
from django.core.urlresolvers import reverse
from django.conf.urls import patterns, include, url
import django.contrib.auth.views as authViews

from .views import *

urlpatterns = [
    # Main app page
    url(r'^$', AppView.as_view(), name="app"),

    # Authentication
    url(r'^login$', authViews.login, {'template_name': 'webapp/login.html' }, name='login'),
    url(r'^logout$', authViews.logout_then_login, name='logout'),
    url(r'^change-password$', authViews.password_change, {
            'template_name': 'webapp/change-password.html',
            'post_change_redirect': 'webapp:change-password-done',
            'current_app': 'webapp'
        }, name='change-password'
    ),
    url(r'^change-password/done$', authViews.password_change_done, {
            'template_name': 'webapp/change-password-done.html',
        }, name='change-password-done'
    ),
    url(r'forgot-password$', authViews.password_reset, {
            'template_name': 'webapp/forgot-password.html',
            'post_reset_redirect': 'webapp:forgot-password-done',
            'email_template_name': 'webapp/email/reset-password-email.txt',
            'subject_template_name': 'webapp/email/reset-password-subject.txt'
        }, name='forgot-password'
    ),
    url(r'^forgot-password/done$', authViews.password_reset_done, {
            'template_name': 'webapp/forgot-password-done.html',
        }, name='forgot-password-done'
    ),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', authViews.password_reset_confirm, {
            'template_name': 'webapp/reset-password.html',
            'post_reset_redirect': 'webapp:reset-password-done'
        }, name='reset-password'
    ),
    url(r'^reset-password/done$', authViews.password_reset_complete, {
            'template_name': 'webapp/reset-password-done.html',
        }, name='reset-password-done'
    ),
]

my2009/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from rest_framework import routers

from django.contrib import admin
admin.autodiscover()

from apps.courses import views as courseViews
from apps.users import views as userViews
from apps.events import views as eventViews
from apps.tasks import views as taskViews
from apps.notifications_api import views as notificationsViews

from apps.webapp import urls as webappUrls
from apps.files import urls as filesUrls
from apps.stats import urls as statsUrls

# API router
router = routers.DefaultRouter()
router.register(r'comments', userViews.CommentViewSet)
router.register(r'comment-thread-subscriptions', userViews.CommentThreadSubscriptionViewSet)
router.register(r'milestones', userViews.MilestoneViewSet)
router.register(r'roles', userViews.RoleViewSet)
router.register(r'taskforces', userViews.TaskForceViewSet)
router.register(r'teams', userViews.TeamViewSet)
router.register(r'users', userViews.UserViewSet)
router.register(r'user-profiles', userViews.UserProfileViewSet)
router.register(r'user-settings', userViews.UserSettingViewSet)
router.register(r'events', eventViews.EventViewSet)
router.register(r'tasks', taskViews.TaskViewSet)
router.register(r'notifications', notificationsViews.NotificationViewSet)
router.register(r'courses', courseViews.CourseViewSet)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my2009.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    # Main page (redirect to web app)
    url(r'^$', RedirectView.as_view(pattern_name='webapp:app', permanent=False)),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    
    # Web app
    url(r'^app/', include(webappUrls, namespace='webapp')),
    
    # API
    url(r'^api/files/', include(filesUrls, namespace='files')),
    url(r'^api/stats/', include(statsUrls, namespace='stats')),
    url(r'^api/', include(router.urls)),
)

apps/webapp/views/AppView.py
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf import settings

class AppView(TemplateView):
    template_name = "webapp/app.html"
    
    def get(self, request, *args, **kwargs):
        # Redirect to login page if not authenticated
        if request.user.is_authenticated():
            return super().get(request, *args, **kwargs)
        else:
            return redirect(settings.LOGIN_URL)

apps/webapp/templates/webapp/change-password-done.html
{% extends 'webapp/page.html' %}

{% block pageTitle %} &raquo; Change password{% endblock %}

{% block pageContent %}
    <div class="container-fluid">
        <div class="col-md-6 col-lg-4">
            <h2>Password change successful</h2>
            <p>Your password was changed.</p>
        </div>
    </div>
{% endblock %}

apps/webapp/templates/webapp/change-password.html
{% extends 'webapp/page.html' %}

{% block pageTitle %} &raquo; Change password{% endblock %}

{% block pageContent %}
    <div class="container-fluid">
        <div class="col-md-6 col-lg-4">
            <h2>Change password</h2>
            
            <form action="{{ request.path }}" method="post">
                {% csrf_token %}

                {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                    </div>
                {% endif %}

                <div class="form-group{% if form.old_password.errors %} has-error{% endif %}">
                    <label class="control-label" for="id_old_password">Old password:</label>
                    <input class="form-control" id="id_old_password" name="old_password" type="password" required>
                </div>
                <div class="form-group{% if form.new_password1.errors %} has-error{% endif %}">
                    <label class="control-label" for="id_new_password1">New password:</label>
                    <input class="form-control" id="id_new_password1" name="new_password1" type="password" required>
                </div>
                <div class="form-group{% if form.new_password2.errors %} has-error{% endif %}">
                    <label class="control-label" for="id_new_password2">New password confirmation:</label>
                    <input class="form-control" id="id_new_password2" name="new_password2" type="password" required>
                </div>
                <button class="btn btn-primary">Change password</button>
            </form>
        </div>
    </div>
{% endblock %}

apps/webapp/templates/webapp/forgot-password-done.html
{% extends 'webapp/page.html' %}

{% block pageTitle %} &raquo; Change password{% endblock %}

{% block pageContent %}
    <div class="container-fluid">
        <div class="col-md-6 col-lg-4">
            <h2>Password reset successful</h2>
            <p>We've emailed you instructions for setting your password. You should be receiving them shortly.</p>
            <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
            <p>
                <a href="{% url 'webapp:login' %}">Return to login page</a>
            </p>
        </div>
    </div>
{% endblock %}

apps/webapp/templates/webapp/forgot-password.html
{% extends 'webapp/page.html' %}

{% block pageTitle %} &raquo; Reset password{% endblock %}

{% block pageContent %}
    <div class="container-fluid">
        <div class="col-md-6 col-lg-4">
            <h2>Reset password</h2>
            
            <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
            
            <form action="{{ request.path }}" method="post">
                {% csrf_token %}

                {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                    </div>
                {% endif %}

                <div class="form-group{% if form.email.errors %} has-error{% endif %}">
                    <label class="control-label" for="id_email">Email address:</label>
                    <input class="form-control" id="id_email" maxlength="254" name="email" type="email" required>
                </div>

                <button class="btn btn-primary">Reset password</button>
            </form>

            <p><br>
                <a href="{% url 'webapp:login' %}">Return to login page</a>
            </p>
        </div>
    </div>
{% endblock %}

apps/webapp/templates/webapp/login.html
{% extends 'webapp/page.html' %}
{% load staticfiles %}

{% block pageTitle %} &raquo; Login{% endblock %}

{% block pageContent %}
<div id="login-page">
    <div class="container">
        <form class="form-login" action="{{ request.path }}" method="post">{% csrf_token %}
        	<input type="hidden" name="next" value="{{ next }}" />
            <h2 class="form-login-heading">Sign in</h2>
            <div class="login-wrap">
                {% if form.errors %}
                    <div class="alert alert-danger">
                        Invalid username or password.
                    </div>
                {% endif %}
                <input id="id_username" maxlength="254" name="username" type="text" class="form-control" placeholder="User ID" autofocus>
                <br>
                <input id="id_password" name="password" type="password" class="form-control" placeholder="Password">
                <label class="checkbox">
                    <span class="pull-right">
                        <a href="{% url 'webapp:forgot-password' %}">Forgot your password?</a>
                    </span>
                </label>
                <button class="btn btn-theme btn-block" type="submit"><i class="fa fa-lock"></i> Sign in</button>
            </div>
        </form>	  	
    </div>
</div>
{% endblock %}

apps/webapp/templates/webapp/page.html
{% load staticfiles %}
{% load pipeline %}

<!DOCTYPE html>
<html lang="en"{% block htmlAttr %}{% endblock %}>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{% block overridePageTitle %}My2009{% block pageTitle %}{% endblock %}{% endblock %}</title>

        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Ruda:400,700,900">
        {% stylesheet 'app' %}

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>

        <script src="{% static 'bower_components/underscore/underscore-min.js' %}"></script>

        <script src="{% static 'bower_components/moment/moment.js' %}"></script>
        <script src="{% static 'bower_components/fullcalendar/dist/fullcalendar.min.js' %}"></script>
        
        <script src="{% static 'bower_components/angular/angular.min.js' %}"></script>
        <script src="{% static 'bower_components/angular-cookies/angular-cookies.min.js' %}"></script>
        <script src="{% static 'bower_components/angular-ui-router/release/angular-ui-router.min.js' %}"></script>
        <script src="{% static 'bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js' %}"></script>
        <script src="{% static 'bower_components/angular-ui-indeterminate/dist/indeterminate.min.js' %}"></script>
        <script src="{% static 'bower_components/angular-ui-calendar/src/calendar.js' %}"></script>
        <script src="{% static 'bower_components/angular-file-upload/dist/angular-file-upload.min.js' %}"></script>
        <script src="{% static 'bower_components/angular-google-chart/ng-google-chart.js' %}"></script>

        {% block pageScriptHead %}{% endblock %}
    </head>

    <body{% block bodyAttr %}{% endblock %}>
        {% block pageContent %}{% endblock %}
    </body>
</html>

apps/webapp/templates/webapp/reset-password-done.html
{% extends 'webapp/page.html' %}

{% block pageTitle %} &raquo; Change password{% endblock %}

{% block pageContent %}
    <div class="container-fluid">
        <div class="col-md-6 col-lg-4">
            <h2>Password reset successful</h2>
            <p>We've emailed you instructions for setting your password. You should be receiving them shortly.</p>
            <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
            <p>
                <a href="{% url 'webapp:login' %}">Return to login page</a>
            </p>
        </div>
    </div>
{% endblock %}

apps/webapp/templates/webapp/reset-password.html
{% extends 'webapp/page.html' %}

{% block pageTitle %} &raquo; Reset password{% endblock %}

{% block pageContent %}
    <div class="container-fluid">
        <div class="col-md-6 col-lg-4">
            <h2>Reset password</h2>
            
            {% if validlink %}
                <p>Please enter your new password.</p>
                <form action="{{ request.path }}" method="post">
                    {% csrf_token %}

                    {% if form.errors %}
                        <div class="alert alert-danger">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                        </div>
                    {% endif %}

                    <div class="form-group{% if form.new_password1.errors %} has-error{% endif %}">
                        <label class="control-label" for="id_new_password1">New password</label>
                        <input class="form-control" id="id_new_password1" name="new_password1" type="password" required>
                    </div>
                    <div class="form-group{% if form.new_password2.errors %} has-error{% endif %}">
                        <label class="control-label" for="id_new_password2">Confirm new password</label>
                        <input class="form-control" id="id_new_password2" name="new_password2" type="password" required>
                    </div>

                    <button class="btn btn-primary">Change password</button>
                </form>
            {% else %}
                <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
            {% endif %}

            <p><br>
                <a href="{% url 'webapp:login' %}">Return to login page</a>
            </p>
        </div>
    </div>
{% endblock %}